[package]
name = "embedded-text"
version = "0.0.2"
license = "MIT"
description = "TextBox for embedded-graphics"
repository = "https://github.com/bugadani/embedded-text"
authors = ["Dániel Buga <bugadani@gmail.com>"]
keywords = ["embedded-graphics", "textbox", "text"]
categories = ["no-std", "embedded", "graphics"]
edition = "2018"

exclude = [
    ".gitignore",
    ".github/",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "0.6.2"

[dev-dependencies]
embedded-graphics-simulator = "0.2.0"