[package]
name = "embedded-text"
version = "0.1.0"
authors = ["Dániel Buga <bugadani@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "0.6.2"

[dev-dependencies]
embedded-graphics-simulator = "0.2.0"