name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.41.0  # MSRV

    steps:
    - name: install_dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev imagemagick

    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
        components: rustfmt, clippy

    - name: Build
      run: cargo build --verbose

    - name: Build examples
      run: cargo build --examples --verbose

    - name: Run tests
      run: |
        cargo test --verbose --release
        cargo test --verbose --release --all-features

    - name: Check example images
      run: |
        mkdir -p ./target/screenshots
        EG_SIMULATOR_DUMP="./target/screenshots/left.png" cargo run --example left
        compare -metric AE ./assets/left.png ./target/screenshots/left.png result.png
        EG_SIMULATOR_DUMP="./target/screenshots/right.png" cargo run --example right
        compare -metric AE ./assets/right.png ./target/screenshots/right.png result.png
        EG_SIMULATOR_DUMP="./target/screenshots/center.png" cargo run --example center
        compare -metric AE ./assets/center.png ./target/screenshots/center.png result.png
        EG_SIMULATOR_DUMP="./target/screenshots/justified.png" cargo run --example justified
        compare -metric AE ./assets/justified.png ./target/screenshots/justified.png result.png
        EG_SIMULATOR_DUMP="./target/screenshots/specials.png" cargo run --example specials
        compare -metric AE ./assets/specials.png ./target/screenshots/specials.png result.png
        EG_SIMULATOR_DUMP="./target/screenshots/variable_width.png" cargo run --example variable_width
        compare -metric AE ./assets/variable_width.png ./target/screenshots/variable_width.png result.png
        EG_SIMULATOR_DUMP="./target/screenshots/vertical.png" cargo run --example vertical
        compare -metric AE ./assets/vertical.png ./target/screenshots/vertical.png result.png
        EG_SIMULATOR_DUMP="./target/screenshots/colored_text.png" cargo run --example colored_text
        compare -metric AE ./assets/colored_text.png ./target/screenshots/colored_text.png result.png
